# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KSpot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Kingfisher'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'SnapKit'
pod 'SwiftyJSON'
pod 'Alamofire'


  # Pods for KSpot

end
